### ISSUE TITLE
SGE on shared disk

### ISSUE THREAD

**Issue by mperov** [daimh/sge#14]
Hello! Your project is very cool! I'm glad to try it!
I would like to help you to improve, e.g. some changing of README. If I will have free time I will create some merge requests:)

So I'd like to ask you about running SGE on shared disk. Is it possible? Most of clusters have NFS disk which contain all shared data.
I didn't understand why you set SGE_ROOT in system directory - /opt/sge.

**Comment by daimh** [comment]
Thanks! It will be wonderful it you can improve the README!

Yes, SGE can run on shared disk.  http://gridscheduler.sourceforge.net/howto/nfsreduce.html has more details about shared-nothing or shared-something.

From my own experience, I used to put the whole /opt/sge on a shared NFS storage, but later I only shared 'common' to reduce NFS traffic. In the repo README, I set it up as a shared-nothing, so it is easier for the demo purpose. That's why there is a 'scp' in the commands.

Even if you design a production cluster, shared-nothing has its value because local IO is either faster, or more cost-effective, or both.

/opt/sge has been a standard way to setup SGE in a self-contained directory. I guess the reason is that SGE was designed to run on all kinds of Unix in addition to Linux.

**Comment by mperov** [comment]
@daimh thanks for your answer!

I understood you so I will create symbol link /opt/sge to /path/to/shared/nfs/dir/sge. Of course it will increase NFS traffic, however it will not be problem for my cluster!
